feat(capacity): remove target validity
LibertyDSNP/frequency pull request #1012
Opened 2023-02-01 23:45 UTC by enddynayn

# Goal
Remove target validity when unstaking.
This validation is not needed since a
target-staker relationship existence is
checked when attempting to reduce the Capacity
of a target.

Closes #894

2023-02-01 23:47 UTC, enddynayn commented
Waiting for Jenkins to generate new weights.

2023-02-02 01:12 UTC, enddynayn commented on pallets/capacity/src/weights.rs
> +			.saturating_add(RocksDbWeight::get().reads(4 as u64))
Reads are decreased by one as a result of removing target validation.

2023-02-02 01:14 UTC, enddynayn commented on pallets/capacity/src/weights.rs
> +			.saturating_add(RocksDbWeight::get().reads(1 as u64))
Nice. We improved the reads and writes of on_intitialize in another pr.

2023-02-02 02:09 UTC, shannonwells approved these changes
do it to it

2023-02-02 14:07 UTC, johnmela requested changes
Looks good!

Let's also remove line 95 from `capacity/src/benchmarking.rs`
`register_provider::<T>(target, "Foo");`

2023-02-02 15:41 UTC, johnmela approved these changes

2023-02-02 15:45 UTC, merged