stable capacity here we come
LibertyDSNP/frequency pull request #1200
Opened 2023-03-08 01:54 UTC by enddynayn

# Goal
The goal of this PR is 

Closes

2023-03-08 19:42 UTC, enddynayn commented on pallets/frequency-tx-payment/src/capacity_payment.rs
> +use pallet_messages::Call as MessagesCall;
remove

2023-03-08 19:43 UTC, enddynayn commented on pallets/frequency-tx-payment/src/lib.rs
> +		let base_fee = T::WeightToFee::weight_to_fee(&capped_weight);
Make this a constant?

2023-03-08 19:44 UTC, enddynayn commented
Any suggestions on how to improve the design of this are welcome!

2023-03-08 19:44 UTC, enddynayn commented on pallets/frequency-tx-payment/src/capacity_stable_weights.rs
> +	fn grant_delegation(s: u32, ) -> Weight {
@wilwade can you please check these to see if we are missing something?

2023-03-08 19:59 UTC, shannonwells commented on pallets/frequency-tx-payment/src/lib.rs
> +	/// The call has not no stable weights associated with it.
```suggestion
	/// The call has no stable weights associated with it.
```

2023-03-08 20:06 UTC, shannonwells reviewed
I'm a bit concerned about duplicated capacity call lists. I was imaginging one entity, maybe an enum of calls and an implementation of Contains and GetStableWeight on the enum.  I don't know what you've tried already but maybe we can pair on this.

2023-03-08 21:12 UTC, enddynayn commented
> I'm a bit concerned about duplicated capacity call lists. I was imaginging one entity, maybe an enum of calls and an implementation of Contains and GetStableWeight on the enum.  I don't know what you've tried already but maybe we can pair on this.

I totally agree. I tried the enum thing as you suggested but could not get it to work.

2023-03-08 22:07 UTC, enddynayn commented on pallets/frequency-tx-payment/src/lib.rs
> +		let base_fee = Self::weight_to_fee(T::BlockWeights::get().get(class).base_extrinsic);
Maybe update to a constant.

2023-03-09 17:19 UTC, shannonwells commented on pallets/frequency-tx-payment/src/lib.rs
> +		type CapacityCalls: GetStableWeight<<Self as Config>::RuntimeCall, Weight>;
❤️

2023-03-09 18:36 UTC, shannonwells requested changes
I think converting Contains trait to GetStableWeight was a great change.
The only blocking comment I have is about the Error name.

2023-03-09 18:41 UTC, enddynayn commented on pallets/frequency-tx-payment/src/lib.rs
> +	CallHasNoStableWeights,
ahh good catch.

2023-03-09 18:45 UTC, enddynayn commented on pallets/frequency-tx-payment/src/lib.rs
> +		let base_fee = Self::weight_to_fee(T::BlockWeights::get().get(class).base_extrinsic);
Ah yeah, I am just waiting for @wilwade on this one.

2023-03-09 18:48 UTC, enddynayn commented on pallets/frequency-tx-payment/src/lib.rs
> +				let extrinsic_weight = T::CapacityCalls::get_stable_weight(call)
Me too. Feel free to let me know if you have any good ideas here. I thought about it here but could not find a good pattern and name.

2023-03-09 18:52 UTC, shannonwells commented on pallets/frequency-tx-payment/src/lib.rs
> +				let extrinsic_weight = T::CapacityCalls::get_stable_weight(call)
better

2023-03-09 18:53 UTC, shannonwells approved these changes

2023-03-09 18:56 UTC, enddynayn commented on pallets/frequency-tx-payment/src/lib.rs
> +				let extrinsic_weight = T::CapacityCalls::get_stable_weight(call)
Nothing changed 😄.

2023-03-09 19:51 UTC, johnmela commented on pallets/frequency-tx-payment/src/lib.rs
> +		let (_fee, initial_payment) = self.withdraw_fee(who, &call, info, len)?;
I like this as well

2023-03-09 19:57 UTC, johnmela approved these changes
Approved 👍 

It would be a nice to have to get a sanity check in the form of a test that ensures that white listed call weight is stable. Non blocking of course.

2023-03-09 21:55 UTC, enddynayn commented on pallets/frequency-tx-payment/src/lib.rs
> +		let base_fee = Self::weight_to_fee(T::BlockWeights::get().get(class).base_extrinsic);
I am going to create a ticket to update if we decide to do so.

2023-03-09 21:56 UTC, enddynayn commented
> Approved 👍
> 
> It would be a "nice to have" to get a sanity check in the form of a test that ensures that white listed call fees are stable. Non blocking of course.

The test is there, but maybe I misunderstood the test you are thinking about.

2023-03-09 21:57 UTC, merged