Removed nonce from KeyInfo and AddKeyData
LibertyDSNP/frequency pull request #330
Opened 2022-08-11 21:18 UTC by dopatraman

# Goal
The goal of this PR is to remove the `nonce` field from the `KeyInfo` class.

Closes #193 

# Discussion
We no longer need the `nonce` field to prevent Replay Attacks on adding keys.

Note: This PR also removes the `nonce` field from the `AddKeyData` struct. It seems like this field was not in use.

# Checklist
- [ ] Updated the js/api-augment code if a custom RPC added/changed
- [ ] Tests added
- [ ] Weights updated

2022-08-11 23:00 UTC, shannonwells approved these changes
Seems legit

2022-08-11 23:00 UTC, shannonwells commented on pallets/msa/src/weights.rs
> +		(69_036_000 as Weight)
That's weird, I'd think removing data from this struct would lower the weight. I guess it's your hardware.

2022-08-11 23:06 UTC, enddynayn commented
I do not think we want to remove nonce right? Can we hold off till tomorrow before merging.

2022-08-12 02:41 UTC, saraswatpuneet requested changes
Keeping it as blocker. I do not think we confirmed removing nonce yet

2022-08-12 13:28 UTC, wilwade commented
One other note. If we do remove nonce and expired (#308), then we likely want to remove KeyInfo struct entirely.

2022-08-30 16:20 UTC, wilwade commented
Closing as https://github.com/LibertyDSNP/frequency/issues/193 has switched up.

2022-08-30 16:20 UTC, closed without merging