Update to .9.28
LibertyDSNP/frequency pull request #451
Opened 2022-09-20 23:28 UTC by saraswatpuneet

Update Substrate to its latest release of `v0.9.28` and all pinned versions of `jsonrpsee` to `0.15.1`. The minor version change from 0.14.x to 0.15.x of `jsonrpsee` is code breaking and therefore must be updated along with the Substrate since the new release depends on `0.15.1`.

https://github.com/paritytech/polkadot/releases/tag/v0.9.28

Then go to v0.9.29: https://github.com/paritytech/polkadot/releases/tag/v0.9.29
- [ ] Update substrate to 0.9.28
- [ ] Update Substrate to `v0.9.29` (BLOCKER: orml has not yet released .9.29)
- [x] Update `jsonrpsee` to `0.15.1` (Substrate ^9.27 depends on this version)

2022-09-21 20:08 UTC, johnmela approved these changes

2022-09-21 21:45 UTC, johnmela requested changes
Do we want to update the polkadot images in docker-compose as well?

2022-09-21 22:23 UTC, saraswatpuneet commented
@johnmela updated image versions

2022-09-22 12:50 UTC, johnmela approved these changes
Looks good!

2022-09-22 17:32 UTC, merged